name = "ODE_PDE_Julia"
uuid = "b7b2d78a-1a2c-4d54-9a63-3d93b4c84e0a"
authors = ["Abolfazl Mohammadijoo <a.mohamadijoo@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
